# Generated by Django 3.1 on 2020-09-18 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(help_text='文件的UUID', primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='')),
                ('name', models.CharField(blank=True, editable=False, help_text='文件名', max_length=100, null=True)),
            ],
        ),
    ]
