# Generated by Django 3.1 on 2020-09-18 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file', '0001_initial'),
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(help_text='提交ID', primary_key=True, serialize=False)),
                ('submit_time', models.DateTimeField(auto_now_add=True, help_text='提交时间')),
                ('problem', models.ForeignKey(help_text='提交的题目', null=True, on_delete=django.db.models.deletion.CASCADE, to='problem.problem')),
                ('submit_files', models.ManyToManyField(help_text='提交的文件（代码等）', to='file.File')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionResult',
            fields=[
                ('id', models.AutoField(help_text='提交结果ID', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('JUDGING', 'Judging'), ('DONE', 'Done'), ('ERROR', 'Error')], help_text='The current status of this submission result', max_length=20)),
                ('possible_failure', models.CharField(choices=[('CE', 'Compile Error'), ('RLE', 'Resource Limitation Exceeded'), ('TLE', 'Time Limitation Exceeded'), ('WA', 'Wrong Answer'), ('NONE', 'No Error'), ('NA', 'Not available')], help_text='Possible failure of this submission result', max_length=20)),
                ('submit_time', models.DateTimeField(auto_now_add=True, help_text='结果提交时间')),
                ('grade', models.IntegerField(help_text='本测试点所得的分数')),
                ('log', models.TextField(blank=True, help_text='The log generated along the process')),
                ('app_data', models.TextField(blank=True, help_text='Data associated with this result (waveform, etc)')),
                ('submission', models.ForeignKey(help_text='某个测试点结果所属的提交', on_delete=django.db.models.deletion.CASCADE, to='submission.submission')),
                ('testcase', models.ForeignKey(help_text='某个测试点结果所属的测试点', on_delete=django.db.models.deletion.CASCADE, to='problem.testcase')),
            ],
        ),
    ]
