# Generated by Django 3.2.18 on 2024-06-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_password_strong',
            field=models.BooleanField(default=False, help_text='Whether the password is strong enough'),
        ),
    ]
