# Generated by Django 3.2.6 on 2022-02-21 12:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0006_auto_20210918_2120'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='讨论标题', max_length=50)),
                ('description', models.TextField(help_text='讨论内容描述（文字）')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='修改时间')),
                ('creator', models.ForeignKey(help_text='发帖人', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(help_text='讨论相关题目', on_delete=django.db.models.deletion.CASCADE, to='problem.problem')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(help_text='评论')),
                ('is_removed', models.BooleanField(default=False)),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='修改时间')),
                ('parent', models.ForeignKey(blank=True, default=None, help_text='父评论', null=True, on_delete=django.db.models.deletion.CASCADE, to='discussion.comment')),
                ('replyer', models.ForeignKey(help_text='回帖人', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(help_text='帖子', on_delete=django.db.models.deletion.CASCADE, to='discussion.topic')),
            ],
        ),
    ]
