# Generated by Django 3.2.12 on 2022-02-28 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0003_auto_20220225_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, help_text='父评论', null=True, on_delete=django.db.models.deletion.SET_NULL, to='discussion.comment'),
        ),
    ]
