# Generated by Django 3.2.12 on 2022-02-28 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0004_alter_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_removed',
        ),
    ]
