# Generated by Django 3.1 on 2020-09-18 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(help_text='题目ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='题目名字', max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='题目的创建时间')),
                ('deadline_time', models.DateTimeField(blank=True, help_text='题目的截止时间', null=True)),
                ('level', models.IntegerField(default=1, help_text='难度等级')),
                ('tags', models.CharField(blank=True, help_text='题目标签', max_length=100)),
                ('description', models.TextField(help_text='题目描述（文字）')),
                ('description_input', models.TextField(help_text='输入描述（文字）')),
                ('description_output', models.TextField(help_text='输出描述（文字）')),
                ('app_data', models.TextField(blank=True, help_text='样例用到的波形图')),
                ('description_files', models.ManyToManyField(blank=True, help_text='描述文件', related_name='description', to='file.File')),
                ('judge_files', models.ManyToManyField(blank=True, help_text='评测所用文件', related_name='judge', to='file.File')),
                ('template_code_file', models.ForeignKey(blank=True, help_text='模板代码文件', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_code', to='file.file')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(help_text='Testcase ID', primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('SIM', 'Behavioral Simulation'), ('SYNTHSIM', 'Gate-Level Simulation')], help_text='测试点类型', max_length=20)),
                ('grade', models.IntegerField(default=10, help_text='测试点分值')),
                ('problem', models.ForeignKey(help_text='测试点所属的题目', on_delete=django.db.models.deletion.CASCADE, to='problem.problem')),
                ('testcase_files', models.ManyToManyField(blank=True, help_text='测试点所用文件', to='file.File')),
            ],
        ),
    ]
