# Generated by Django 3.1 on 2020-12-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='mem_limit',
            field=models.IntegerField(default=128, help_text='测试内存限制 (MiB)'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='time_limit',
            field=models.IntegerField(default=60, help_text='测试时间限制 (s)'),
        ),
    ]
