# Generated by Django 3.1 on 2021-01-15 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problem', '0003_problem_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='owner',
            field=models.ForeignKey(help_text='题目创建者', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
