# Generated by Django 3.2.6 on 2021-09-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_auto_20210115_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='logic_id',
            field=models.IntegerField(help_text='题目ID', null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]