# Generated by Django 3.2.6 on 2021-10-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0006_auto_20210918_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='views',
            field=models.PositiveIntegerField(default=0, help_text='浏览量'),
        ),
    ]
