# Generated by Django 3.2.12 on 2022-11-01 12:43

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
        ('problem', '0006_auto_20210918_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='template_code_files',
            field=models.ManyToManyField(blank=True, help_text='模板代码文件', null=True, related_name='template_codes', to='file.File'),
        ),
    ]
