# Generated by Django 3.2.12 on 2022-11-01 13:06

from django.db import migrations


def forward(apps, schema_editor):
    Problem = apps.get_model("problem", "Problem")
    for problem in Problem.objects.all():
        problem.template_code_files.add(problem.template_code_file)

class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0007_problem_template_code_files'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
